name: test
on:
  push:
    branches:
    - '**'
jobs:
  test:
    strategy:
      matrix:
        go-version:
          - 1.12.x
          - 1.13.x
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      run: go test -cover -race ./...
